# Generated by Django 5.1.6 on 2025-03-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [("can_block_user", "can block user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
