# Generated by Django 5.1.6 on 2025-03-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_users", "0003_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, null=True),
        ),
    ]
