# Generated by Django 5.1.5 on 2025-01-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_sending", models.DateTimeField(verbose_name="Время начала")),
                ("last_sending", models.DateTimeField(verbose_name="Время конца")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ended", "Завершена"),
                            ("created", "Создана"),
                            ("started", "Запущена"),
                        ],
                        max_length=7,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["first_sending", "last_sending", "status"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_letter", models.CharField(max_length=100, unique=True)),
                ("body_letter", models.TextField(verbose_name="комментарий")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
                "ordering": ["subject_letter", "body_letter"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100, unique=True)),
                ("fullname", models.CharField(max_length=100)),
                ("comment", models.TextField(verbose_name="комментарий")),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["email", "fullname"],
            },
        ),
        migrations.CreateModel(
            name="AttemptMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_attempt",
                    models.DateTimeField(verbose_name="Дата и время попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("not success", "Не успешно")],
                        max_length=11,
                        verbose_name="Статус",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="web_project.mailing",
                        verbose_name="Попытка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "ordering": ["date_attempt", "status", "answer", "mailing"],
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="web_project.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipient",
            field=models.ManyToManyField(
                related_name="mailings",
                to="web_project.recipient",
                verbose_name="Клиент",
            ),
        ),
    ]
