# Generated by Django 5.1.5 on 2025-01-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptmailing",
            name="answer",
            field=models.TextField(
                editable=False, verbose_name="Ответ почтового сервера"
            ),
        ),
        migrations.AlterField(
            model_name="attemptmailing",
            name="date_attempt",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время попытки"
            ),
        ),
        migrations.AlterField(
            model_name="attemptmailing",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("not success", "Не успешно")],
                editable=False,
                max_length=11,
                verbose_name="Статус",
            ),
        ),
    ]
