# Generated by Django 5.1.5 on 2025-01-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_project", "0002_alter_attemptmailing_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="first_sending",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Время начала"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="last_sending",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Время конца"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("ended", "Завершена"),
                    ("created", "Создана"),
                    ("started", "Запущена"),
                ],
                default="Создана",
                editable=False,
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject_letter",
            field=models.CharField(max_length=100, unique=True, verbose_name="тема"),
        ),
    ]
