# Generated by Django 5.1.6 on 2025-02-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_project", "0003_alter_mailing_first_sending_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("ended", "Завершена"),
                ],
                default="created",
                editable=False,
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
