# Generated by Django 5.1.6 on 2025-03-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_project", "0005_mailing_owner_recipient_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
