# Generated by Django 5.1.6 on 2025-03-03 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_project", "0006_mailing_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptmailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца попытки рассылки",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец попытки рассылки",
            ),
        ),
    ]
