# Generated by Django 5.1.6 on 2025-03-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_project", "0009_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["first_sending", "last_sending", "status"],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
