# Generated by Django 5.1.6 on 2025-03-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_project", "0010_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["first_sending", "last_sending", "status"],
                "permissions": [("can_disabling_mailings", "can disabling mailings")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
