# Generated by Django 5.1.6 on 2025-03-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_project", "0011_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
